### ISSUE TITLE
MOB3 - Gestion des comptes utilisateurs - comptes locaux

### ISSUE THREAD

**Issue by lsr57** [InTechSA/lux-mobility-backend#2]
- Inscription d’un nouvel utilisateur
- Connexion de l’utilisateur
- Gestion de la session
- Fonction “Mot de passe oublié ?”

**Comment by Valko54** [comment]
Point 09/12/16:

- [x] Inscription d'un nouvel utilisateur 
- [x] Connexion de l'utilisateur avec Email / Mot de passe
- [x] Gestion de la session - Stratégie par jeton
- [ ] Fonction "Mot de passe oublié ?"

**Comment by lsr57** [comment]
Question : avec quel serveur smtp envoyer les e-mails de réinitialisation de mot de passe ?

**Comment by lsr57** [comment]
Pull request => https://github.com/InTechSA/lux-mobility-backend/pull/8

**Comment by Valko54** [comment]
Point 23/12/16:

Pull request validé pour les tâches suivantes:
- ✅ Inscription d'un nouvel utilisateur 
- ✅ Connexion de l'utilisateur avec Email / Mot de passe
- ✅ Gestion de la session - Stratégie par jeton

La fonction "Mot de passe oublié ?" n'est pas encore finalisé car la redirection vers l'application mobile n'est pas fonctionnelle. Je crée une issue dédiée.
