### ISSUE TITLE
MOB4 - Gestion des comptes utilisateurs - comptes Facebook

### ISSUE THREAD

**Issue by lsr57** [InTechSA/lux-mobility-backend#3]

**Comment by Valko54** [comment]
Point 09/12/2016:

- [x] Mise en place de la stratégie Facebook-Token avec Passport
- [ ] Création d'un compte développeur Facebook dédié à l'application
- [ ] Gestion de la configuration 

Questions:

- Qui s'occupe de la création et de la gestion du compte développeur Facebook ?

**Comment by bsisic42** [comment]
[fb for dev] account created

**Comment by lsr57** [comment]
Pull request => https://github.com/InTechSA/lux-mobility-backend/pull/7
