### ISSUE TITLE
Ne pas exposer les configurations

### ISSUE THREAD

**Issue by Valko54** [InTechSA/lux-mobility-backend#4]
Certaines configurations de développement se sont retrouvés sur Github, il est préférable de mettre aucun fichier de configuration sur Github.

Néanmoins, nous pouvons laisser un squelette des fichiers de configuration.

- [x] Mettre en place un squelette de la configuration requise
- [x] Vider l'ensemble des valeurs présentes dans les configurations

**Comment by lsr57** [comment]
Il reste à faire la génération du squelette. Qui s'en occupe ?

**Comment by Valko54** [comment]
@bsisic42, je te propose de terminer cette issue en ajoutant la tâche de génération de la configuration. On pourra utiliser cette routine sur Dokku + Variables d'environnements pour éviter de mettre ces informations sur Github ;-)

**Comment by Valko54** [comment]
Point 23/12/16 - Sera mis en place lors de la validation de feat-MOB4
