### ISSUE TITLE
Feature - Mot de passe oublié ?

### ISSUE THREAD

**Issue by Valko54** [InTechSA/lux-mobility-backend#9]
- [x] Configuration du service Mail (nodemailer)
- [x] Création du lien avec un jeton temporaire
- [x] Envoi du mail
- [x] Configurer l'environnement avec les serveurs de la société ION
- [x] Elaboration de l'écran pour réinitialiser son mot de passe
- [x] Rediriger l'utilisateur sur l'écran de réinitialisation de son mot de passe lorsqu'il clique sur le lien présent dans le mail

**Comment by Valko54** [comment]
Point 23/12/2016:

- ✅ Configuration du service Mail (nodemailer)
- ✅ Création du lien avec un jeton temporaire
- ✅ Envoi du mail
- 🔴 Configurer l'environnement avec les serveurs de la société ION
- 🔴 Elaboration de l'écran pour réinitialiser son mot de passe
- 🔴 Rediriger l'utilisateur sur l'écran de réinitialisation de son pot de passe lorsqu'il clique sur le lien présent dans le mail

**Comment by lsr57** [comment]
Pull request https://github.com/InTechSA/lux-mobility-backend/pull/10
Ecran de réinitialisation du mot de passe
Lien pour réinitialiser son mot de passe en étant redirigé sur l'application

**Comment by Valko54** [comment]
Point 27/01/2017:

✅ Configuration du service Mail (nodemailer)
✅ Création du lien avec un jeton temporaire
✅ Envoi du mail
✅ Configurer l'environnement avec les serveurs de la société ION
✅ Elaboration de l'écran pour réinitialiser son mot de passe
✅ Rediriger l'utilisateur sur l'écran de réinitialisation de son pot de passe lorsqu'il clique sur le lien présent dans le mail
